### ISSUE TITLE
nested makeSepBy parsers causes hang

### ISSUE THREAD

**Issue by cdbzb** [shimpe/scparco#1]
Hi Stefan - the following hangs on my system:

ParserFactory.makeSepBy(ParserFactory.makeWs).(
		ParserFactory.makeSepBy(StrParser(",")).(ParserFactory.makeFloatParser)
).run("3,3,3 4,4,4").result

I would expect [[3.0,3.0,3.0],[4.0,4.0,4.0]] unless I have misunderstood?

**Comment by shimpe** [comment]
This one would work: 

ParserFactory.makeSepBy(ParserFactory.makeWsOne).(
ParserFactory.makeSepBy(StrParser(",")).(ParserFactory.makeFloatParser)
).run("3,3,3 4,4,4").result

Trying to optionally separate something by whitespace that can be completely empty leads to an infinite loop because it  matches infinitely many empty strings without making any progress.

**Comment by cdbzb** [comment]
Ah thanks I missed that makeWs was Optional !
